---
title: "Correlation"
date: "Last Updated: `r format(Sys.time(), '%d, %B, %Y at %H:%M')`"
output:
  github_document:
    html_preview: true
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Body data set

```{r}
library(tidyverse)
data <- read_csv('data/body.csv')
```
```{r}
cor.test(data$ChestDepth, data$ElbowDia)
plot(data$ChestDepth, data$ElbowDia)
```

# Vik data set

```{r}
data <- read_csv('data/vik_table_9_2.csv')
result <- cor.test(data$X1, data$Y)
plot(data$X1, data$Y)

result
```

## Calculating the confidence intervals

```{r}
# Note that the confidence interval is not symmetric around the
# estimated correlation value

estimate <- result$estimate
lower <- result$conf.int[1]
upper <- result$conf.int[2]

values <- c(lower, estimate, upper)
delta1 <- estimate - lower
delta2 <- estimate - upper
deltas <- c(delta1, delta2)

values
deltas

```
## Get p value manually

Get the sample correlation.

```{r}
sample_correlation <- cor(data$X1, data$Y)
sample_correlation
```

## Calculate the t-value

```{r}
n<-length(data$X1) 
tvalue <- sample_correlation * sqrt((n-2)/(1 - sample_correlation^2))
tvalue
```

## Calculate p value
Per default R conducts a two-sided test using the following code:


```{r}
df<-n-2
pvalue <- 2 * pt(tvalue, df)
pvalue
```

# Demo of confidence intervals for large r

```{r}
library(faux)
data <- rnorm_multi(n= 10, vars = 2, r=0.80)
result <- cor.test(data$X1, data$X2)

result

# Note that the confidence interval is not symmetric around the
# estimated correlation value

estimate <- result$estimate
lower <- result$conf.int[1]
upper <- result$conf.int[2]

values <- c(lower, estimate, upper)
delta1 <- estimate - lower
delta2 <- estimate - upper
deltas <- c(delta1, delta2)

values
deltas
```

